### ISSUE TITLE
Sattelite dropper - Ignoring blacklists

### ISSUE THREAD

**Issue by GameBurrow** [JanPanthera/JP_X4Mods_2023#1]
It seems that this mod doesn't get along with blacklists well. Neither sector travel nor sector activity blacklists seem to work properly.

**Comment by JanPanthera** [comment]
Please describe the settings you have configured on the order screen, including the blacklist and how it was configured. Also, remember that I can only assist with the information I have on hand; I cannot help with vague issues like 'it doesn't work'. ;-)

**Comment by GameBurrow** [comment]
Apologies for the long delay in response.  Essentially I tried to add BUC related sectors to blacklist so that sattelites wouldn't be dropped there as BUC destroy them almost immediately.

I'm not 100% sure but the issue boils down to this:
- If I change blacklists after the default order is set, the changes don't reflect (or if they do, they do that with huge delay)
- It's unclear if the mod looks Sector Activity blacklist or Sector Travel blacklist, when I try to set only 1 of them (tried both), it seems to ignore it but if I set both blacklist, then it seems to start ignoring them

**Comment by JanPanthera** [comment]
In short, you block sectors with the sector travel blacklist and objects by owner (stations) with an sector activity blacklist. The delay comes from how the script works. If the ship is already flying to a target, off course the blacklist change will not affect it. Would be too much to check for that too. And there is a giant delay from the blacklist system itself, a game problem. And there is also a bug within the blacklist system, if you just tick the restrict all factions option, that does not work. Nothing i can do about.

**Comment by GameBurrow** [comment]
Thanks for explanation, understood. Thanks
